# Site Settings
baseurl: ""
url: "https://JunHyxxn.github.io"

# Blog Settings
theme_settings:
  title: JunHyxxn Blog
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/GithubProfile.jpg
    username: JunHyxxn
    description: Inha Univ. Department of Statistics & CS
    # experience:
    #   - start:
    #     end:
    #     experience:
    # skills:
    #   - skill:
    #     value: 85 # Percent value

  # Icons
  icons:
    email: ihrug000@gmail.com
    # linkedin: # Full URL
    github: JunHyxxn
    # gitlab:
    # bitbucket:
    # google_plus:
    # twitter:
    # youtube:
    # facebook:
    # instagram:

  # Disqus
  disqus_shortname: JunHyxxn

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
